# /tarea_enzzo/docker-compose.yml
version: '3.8'

services:
  cache:
    image: redis:7.0-alpine
    container_name: waze-cache
    ports:
      - "6379:6379"
    networks:
      - cache-net

  storage-api:
    build:
      context: ./storage
      dockerfile: Dockerfile
    container_name: storage-api
    depends_on:
      - mongodb
      - cache
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=waze_traffic
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    ports:
      - "4000:4000"
    networks:
      - storage-net
      - cache-net

  mongodb:
    image: mongo:6.0
    container_name: storage-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - storage-net

  scraper:
    build:
      context: .              
      dockerfile: scraper/Dockerfile
    container_name: waze-scraper
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=storage-mongodb
      - MONGO_PORT=27017
      - MONGO_DB=waze_traffic
    networks:
      - storage-net

  traffic-generator:
    build:
      context: ./traffic-generator
      dockerfile: Dockerfile
    container_name: traffic-generator
    depends_on:
      - storage-api
    environment:
      - STORAGE_API_URL=http://storage-api:4000
    networks:
      - storage-net

networks:
  cache-net:
    name: cache-net
    driver: bridge
  storage-net:
    name: storage-net
    driver: bridge

volumes:
  mongodb_data:
