FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /shared_data && chmod 777 /shared_data

CMD ["python", "traffico.py"]