# /storage/docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: storage-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - storage-net

  storage-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage-api
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=waze_traffic
      - CACHE_API_URL=http://cache:6379
    ports:
      - "4000:4000"
    networks:
      - storage-net
      - cache-net

volumes:
  mongodb_data:

networks:
  storage-net:
    driver: bridge
  cache-net:
    external: true   # compartido con /cache
